name: Build and Upload Artifacts

on:
    # Rebuild on merged pull requests
    pull_request:
        branches:
            - main

    # Allows running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        environment: build
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - StandaloneWindows64 # Build for Windows
                    - StandaloneOSX # Build for macOS (Intel)
                    - StandaloneLinux64 # Build for Linux
                    - WebGL # Build for WebGL
        steps:
            # Checkout
            - uses: actions/checkout@v4
              with:
                  lfs: false

            # Cache
            - uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-${{ matrix.targetPlatform }}
                  restore-keys: Library-x

            # Build
            - uses: game-ci/unity-builder@v4
              env:
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
                  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}

            # Output
            - uses: actions/upload-artifact@v4
              with:
                  name: Build-${{ matrix.targetPlatform }}
                  path: build/${{ matrix.targetPlatform }}

    # Deploy WebGL build to GitHub Pages
    deploy:
        name: Deploy WebGL to GitHub Pages

        # Add a dependency to the build job
        needs: build

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: Build-WebGL
