name: Build and Upload Artifacts

on:
    # Allows running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        enviroment: build
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    # - StandaloneWindows64 # Build for Windows
                    - StandaloneOSX # Build for macOS (Intel)
                    # - StandaloneLinux64 # Build for Linux
                    - WebGL # Build for WebGL
        steps:
            # Checkout
            - uses: actions/checkout@v4
              with:
                  lfs: false

            # Cache
            - uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-${{ matrix.targetPlatform }}
                  restore-keys: Library-x

            # Build
            - uses: game-ci/unity-builder@v4
              env:
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
                  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}

            # Output
            - uses: actions/upload-artifact@v3
              with:
                  name: Build-${{ matrix.targetPlatform }}
                  path: build/${{ matrix.targetPlatform }}
